In [1]:
import numpy as np
import pandas as pd

from scipy.stats import beta
import seaborn as sns
import matplotlib.pyplot as plt
import gc
from tqdm import tqdm


path = './data/'
output = './output/'
figs = './figs/'

player_ext = 'Players_2019.csv'
event_ext = 'Events_2019.csv'
teams_ext = 'Teams.csv'

df = pd.read_csv(path+event_ext)
players = pd.read_csv(path+player_ext)

In [2]:
def get_time_remain(events):
    events['GameID'] = events['Season'].astype(str) + events['DayNum'].astype(str) + events['WTeamID'].astype(str) + events['LTeamID'].astype(str)
    events['OT'] = (events['ElapsedSeconds'] - 2400)/300
    events['OT'] = np.where(events['OT'] < 0, 0, np.ceil(events['OT'])).astype(int)
    events['TimeRemain'] = 2400 + (events['OT'] * 300) - events['ElapsedSeconds']

    return events


df = get_time_remain(df)

In [4]:

def add_score_diff(events):
    
    events['WDiff'] = events['WPoints'] - events['LPoints']
    
    # relative to event
    events.loc[:,'EDiff'] = np.where(events['EventTeamID']==events['WTeamID'], events['WDiff'], -1*events['WDiff'])
    
    
    return events

df = add_score_diff(df)

In [6]:
print(df.EventType.unique())

['assist' 'made2_jump' 'turnover' 'made3_jump' 'foul_pers' 'miss2_jump'
 'reb_def' 'miss3_jump' 'reb_off' 'miss1_free' 'sub_in' 'made1_free'
 'sub_out' 'steal' 'block' 'made2_dunk' 'timeout_tv' 'made2_lay'
 'miss2_lay' 'reb_dead' 'timeout' 'miss2_dunk' 'made2_tip' 'miss2_tip'
 'foul_tech']

In [8]:
df.head()

,EventID,Season,DayNum,WTeamID,LTeamID,WPoints,LPoints,ElapsedSeconds,EventTeamID,EventPlayerID,EventType,GameID,OT,TimeRemain,WDiff,EDiff
0,30099809,2019,1,1104,1380,0,0,18,1380,657441,assist,2019111041380,0,2382,0,0
1,30099810,2019,1,1104,1380,0,2,18,1380,657447,made2_jump,2019111041380,0,2382,-2,2
2,30099811,2019,1,1104,1380,2,2,42,1104,653561,made2_jump,2019111041380,0,2358,0,0
3,30099812,2019,1,1104,1380,0,0,58,1380,657437,turnover,2019111041380,0,2342,0,0
4,30099813,2019,1,1104,1380,0,0,63,1104,653565,assist,2019111041380,0,2337,0,0

In [32]:
# identify pairs and triplets of free throws
# they don't necessarily have consecutive event ids

def get_pairs(events):
    
    events['TotalPoints'] = events['WPoints'] + events['LPoints']
    fts = ['made1_free','miss1_free']
    events['IsFT'] = np.where(events['EventType'].isin(fts), 'free_throw', events['EventType'])
    egb = events.groupby(['GameID','ElapsedSeconds','EventTeamID','IsFT'])['EventID'].count().reset_index()
    egb = egb.loc[(egb['IsFT']=='free_throw')&(egb['EventID']>1)]
    egb['PairOrTrip'] = 1
    egb.loc[egb['EventID']>3, 'PairOrTrip'] = 2
    egb = egb[['GameID','ElapsedSeconds','EventTeamID','PairOrTrip']]
    
    
    # separate ft df to keep event id information
    ft_df = events.loc[events['IsFT']=='free_throw']
    ft_df = ft_df[['EventID','GameID','ElapsedSeconds','EventTeamID','TotalPoints']]
    ft_df = ft_df.sort_values(by=['GameID','ElapsedSeconds','TotalPoints'])
    
    ft_df = pd.merge(ft_df, egb, how='left', left_on=['GameID','ElapsedSeconds','EventTeamID'], right_on=['GameID','ElapsedSeconds','EventTeamID'])

    # last deal is to separate out the 800 or so quadruple and quintuple sets of FTs
    doubles = ft_df.loc[ft_df['PairOrTrip']>1]
    
    egb = ft_df.groupby(['GameID','ElapsedSeconds','EventTeamID'])['EventID'].last().reset_index()
    doubles = doubles.groupby(['GameID','ElapsedSeconds','EventTeamID'])['EventID'].nth(-2).reset_index()
    
    egb = egb[['EventID']]
    doubles = doubles[['EventID']]
    
    print(len(egb))
    egb = pd.concat([egb,doubles], axis=0)
    print(len(egb))
    
    egb['FTPossEnd'] = 1
    
    events = pd.merge(events,egb,how='left',on=['EventID','EventID']) 
    
    events['FTPossEnd'] = events['FTPossEnd'].copy().fillna(0)
    return events
# treat made and missed FTs the same

df = get_pairs(df)

df.loc[df['IsFT']=='free_throw'].head(5)

117145
117425

,EventID,Season,DayNum,WTeamID,LTeamID,WPoints,LPoints,ElapsedSeconds,EventTeamID,EventPlayerID,EventType,GameID,OT,TimeRemain,WDiff,EDiff,IsFT,TotalPoints,FTPossEnd
18,30099827,2019,1,1104,1380,0,0,177,1104,653562,miss1_free,2019111041380,0,2223,0,0,free_throw,0,NaN
22,30099831,2019,1,1104,1380,8,4,177,1104,653562,made1_free,2019111041380,0,2223,4,4,free_throw,12,1.0
103,30099912,2019,1,1104,1380,0,0,607,1380,657437,miss1_free,2019111041380,0,1793,0,0,free_throw,0,NaN
104,30099913,2019,1,1104,1380,0,0,607,1380,657437,miss1_free,2019111041380,0,1793,0,0,free_throw,0,NaN
105,30099914,2019,1,1104,1380,0,0,607,1380,657437,miss1_free,2019111041380,0,1793,0,0,free_throw,0,1.0
113,30099922,2019,1,1104,1380,0,0,673,1104,653561,miss1_free,2019111041380,0,1727,0,0,free_throw,0,NaN
118,30099927,2019,1,1104,1380,21,18,673,1104,653561,made1_free,2019111041380,0,1727,3,3,free_throw,39,1.0
126,30099935,2019,1,1104,1380,0,0,703,1104,653561,miss1_free,2019111041380,0,1697,0,0,free_throw,0,NaN
136,30099945,2019,1,1104,1380,24,18,703,1104,653561,made1_free,2019111041380,0,1697,6,6,free_throw,42,1.0
146,30099955,2019,1,1104,1380,25,18,730,1104,653565,made1_free,2019111041380,0,1670,7,7,free_throw,43,NaN
147,30099956,2019,1,1104,1380,26,18,730,1104,653563,made1_free,2019111041380,0,1670,8,8,free_throw,44,NaN
148,30099957,2019,1,1104,1380,27,18,730,1104,653563,made1_free,2019111041380,0,1670,9,9,free_throw,45,1.0
154,30099963,2019,1,1104,1380,28,18,754,1104,653563,made1_free,2019111041380,0,1646,10,10,free_throw,46,NaN
155,30099964,2019,1,1104,1380,29,18,754,1104,653563,made1_free,2019111041380,0,1646,11,11,free_throw,47,1.0
158,30099967,2019,1,1104,1380,0,0,772,1380,657442,miss1_free,2019111041380,0,1628,0,0,free_throw,0,NaN
159,30099968,2019,1,1104,1380,0,0,772,1380,657442,miss1_free,2019111041380,0,1628,0,0,free_throw,0,1.0
174,30099983,2019,1,1104,1380,29,19,813,1380,657432,made1_free,2019111041380,0,1587,10,-10,free_throw,48,NaN
175,30099984,2019,1,1104,1380,29,20,813,1380,657432,made1_free,2019111041380,0,1587,9,-9,free_throw,49,1.0
178,30099987,2019,1,1104,1380,32,21,846,1380,657432,made1_free,2019111041380,0,1554,11,-11,free_throw,53,NaN
179,30099988,2019,1,1104,1380,32,22,846,1380,657432,made1_free,2019111041380,0,1554,10,-10,free_throw,54,1.0
190,30099999,2019,1,1104,1380,32,23,901,1380,657437,made1_free,2019111041380,0,1499,9,-9,free_throw,55,NaN
191,30100000,2019,1,1104,1380,32,24,901,1380,657437,made1_free,2019111041380,0,1499,8,-8,free_throw,56,1.0
197,30100006,2019,1,1104,1380,33,24,914,1104,653561,made1_free,2019111041380,0,1486,9,9,free_throw,57,NaN
198,30100007,2019,1,1104,1380,34,24,914,1104,653561,made1_free,2019111041380,0,1486,10,10,free_throw,58,1.0
213,30100022,2019,1,1104,1380,0,0,1011,1104,653557,miss1_free,2019111041380,0,1389,0,0,free_throw,0,NaN
218,30100027,2019,1,1104,1380,37,24,1011,1104,653557,made1_free,2019111041380,0,1389,13,13,free_throw,61,1.0
239,30100048,2019,1,1104,1380,0,0,1145,1380,657432,miss1_free,2019111041380,0,1255,0,0,free_throw,0,NaN
243,30100052,2019,1,1104,1380,42,25,1145,1380,657432,made1_free,2019111041380,0,1255,17,-17,free_throw,67,1.0
252,30100061,2019,1,1104,1380,45,25,1196,1104,653569,made1_free,2019111041380,0,1204,20,20,free_throw,70,1.0
254,30100063,2019,1,1104,1380,45,26,1200,1380,657432,made1_free,2019111041380,0,1200,19,-19,free_throw,71,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2543179,32642988,2019,132,1463,1217,64,59,1781,1463,658607,made1_free,201913214631217,0,619,5,5,free_throw,123,NaN
2543180,32642989,2019,132,1463,1217,65,59,1781,1463,658607,made1_free,201913214631217,0,619,6,6,free_throw,124,1.0
2543186,32642995,2019,132,1463,1217,66,59,1814,1463,658595,made1_free,201913214631217,0,586,7,7,free_throw,125,NaN
2543187,32642996,2019,132,1463,1217,67,59,1814,1463,658595,made1_free,201913214631217,0,586,8,8,free_throw,126,NaN
2543188,32642997,2019,132,1463,1217,68,59,1814,1463,658595,made1_free,201913214631217,0,586,9,9,free_throw,127,1.0
2543196,32643005,2019,132,1463,1217,0,0,1872,1463,658593,miss1_free,201913214631217,0,528,0,0,free_throw,0,NaN
2543200,32643009,2019,132,1463,1217,71,59,1872,1463,658593,made1_free,201913214631217,0,528,12,12,free_throw,130,1.0
2543205,32643014,2019,132,1463,1217,73,60,1915,1217,655130,made1_free,201913214631217,0,485,13,-13,free_throw,133,NaN
2543206,32643015,2019,132,1463,1217,73,61,1915,1217,655130,made1_free,201913214631217,0,485,12,-12,free_throw,134,1.0
2543211,32643020,2019,132,1463,1217,73,62,1949,1217,655130,made1_free,201913214631217,0,451,11,-11,free_throw,135,NaN
2543212,32643021,2019,132,1463,1217,73,63,1949,1217,655130,made1_free,201913214631217,0,451,10,-10,free_throw,136,1.0
2543219,32643028,2019,132,1463,1217,0,0,2059,1217,655140,miss1_free,201913214631217,0,341,0,0,free_throw,0,NaN
2543224,32643033,2019,132,1463,1217,79,69,2059,1217,655140,made1_free,201913214631217,0,341,10,-10,free_throw,148,1.0
2543233,32643042,2019,132,1463,1217,81,72,2091,1217,655134,made1_free,201913214631217,0,309,9,-9,free_throw,153,1.0
2543243,32643052,2019,132,1463,1217,0,0,2167,1217,655134,miss1_free,201913214631217,0,233,0,0,free_throw,0,NaN
2543249,32643058,2019,132,1463,1217,86,75,2167,1217,655134,made1_free,201913214631217,0,233,11,-11,free_throw,161,1.0
2543253,32643062,2019,132,1463,1217,87,75,2188,1463,658593,made1_free,201913214631217,0,212,12,12,free_throw,162,NaN
2543254,32643063,2019,132,1463,1217,88,75,2188,1463,658593,made1_free,201913214631217,0,212,13,13,free_throw,163,1.0
2543260,32643069,2019,132,1463,1217,89,75,2235,1463,658606,made1_free,201913214631217,0,165,14,14,free_throw,164,NaN
2543261,32643070,2019,132,1463,1217,90,75,2235,1463,658606,made1_free,201913214631217,0,165,15,15,free_throw,165,1.0
2543266,32643075,2019,132,1463,1217,0,0,2257,1463,658593,miss1_free,201913214631217,0,143,0,0,free_throw,0,NaN
2543268,32643077,2019,132,1463,1217,91,77,2257,1463,658593,made1_free,201913214631217,0,143,14,14,free_throw,168,1.0
2543271,32643080,2019,132,1463,1217,0,0,2273,1217,655138,miss1_free,201913214631217,0,127,0,0,free_throw,0,NaN
2543274,32643083,2019,132,1463,1217,91,78,2273,1217,655138,made1_free,201913214631217,0,127,13,-13,free_throw,169,1.0
2543277,32643086,2019,132,1463,1217,92,78,2284,1463,658596,made1_free,201913214631217,0,116,14,14,free_throw,170,NaN
2543278,32643087,2019,132,1463,1217,93,78,2284,1463,658596,made1_free,201913214631217,0,116,15,15,free_throw,171,1.0
2543286,32643095,2019,132,1463,1217,94,78,2296,1463,658606,made1_free,201913214631217,0,104,16,16,free_throw,172,NaN
2543287,32643096,2019,132,1463,1217,95,78,2296,1463,658606,made1_free,201913214631217,0,104,17,17,free_throw,173,1.0
2543293,32643102,2019,132,1463,1217,96,82,2340,1463,658606,made1_free,201913214631217,0,60,14,14,free_throw,178,NaN
2543294,32643103,2019,132,1463,1217,97,82,2340,1463,658606,made1_free,201913214631217,0,60,15,15,free_throw,179,1.0

In [7]:
# possessions either end on a field goal attempt, a free throw attempt, an offensive rebound, or a turnover
# so let's make a column denoting all of these

fgas = ['made2_jump','made3_jump','made2_dunk','made2_tip','made2_lay','miss2_jump','miss3_jump','miss2_dunk','miss2_tip','miss2_lay']
print(len(fgas))

# identify pairs and triplets of FTs by the same team - mark end of poss


def add_poss_markers(events):
    events['PossBegin'] = 0
    events['PossEnd'] = 0
#     events['PossEnder'] = 0
    
#     events['']
    
#     events['PossEnder'] = np.where(events['EventType'].isin(fgas),1,events['PossEnder'])
    
#     events['PossEnder'] = np.where(events['EventType'].isin(fgas),1,events['PossEnder'])
    
    return events

10